name: Health checks

on:
  schedule:
    - cron: "20 9 * * *"
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-icy-wind-1544.fly.dev/health
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
      - name: Discord Success Webhook
        if: ${{ success() }}
        uses: jasongitmail/fast-webhook@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          json: |
            { "content": "The project ${{ github.repository }} has passed through health check!" }

      - name: Discord Failure Webhook
        if: ${{ failure() || cancelled() }}
        uses: jasongitmail/fast-webhook@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          json: |
            { "content": "Health check failed!" }
